name: MagicalWarps
main: net.katsstuff.bukkit.magicalwarps.WarpsPlugin
version: 2.2.0
authors: [Katrix]
api-version: '1.21'
bootstrapper: net.katsstuff.bukkit.feelingsrelay.ScalaPluginBootstrap
loader: net.katsstuff.bukkit.feelingsrelay.ScalaPluginLoader

dependencies:
  server:
    Vault:
      required: true
    dynmap:
      required: false
      load: BEFORE

permissions:
  magicalwarps.user:
    description: Gives access to normal user permissions
    children:
      magicalwarps.warps.teleport: true
      magicalwarps.warps.list: true
  magicalwarps.mod:
    description: Gives access to mod permissions
    children:
      magicalwarps.mod.send: true
      magicalwarps.mod.set: true
      magicalwarps.mod.modifygroup: true
      magicalwarps.mod.modifyallowed: true
      magicalwarps.mod.setlore: true
      magicalwarps.mod.rename: true
      magicalwarps.mod.setdisplayname: true
      magicalwarps.mod.remove: true
      magicalwarps.mod.warpinfo: true
  magicalwarps.warps.teleport:
    description: Teleport to a warp
    default: true
  magicalwarps.warps.list:
    description: See all warps, optionally for a specific group
    default: true
  magicalwarps.mod.send:
    description: Send a player to a warp
    default: op
  magicalwarps.mod.set:
    description: Sets a new warp
    default: op
  magicalwarps.mod.modifygroup:
    description: Modify a warps group
    default: op
  magicalwarps.mod.modifyallowed:
    description: Modify a warps allowed entities
    default: op
  magicalwarps.mod.setlore:
    description: Sets the lore of a warp
    default: op
  magicalwarps.mod.rename:
    description: Sets the name of a warp
    default: op
  magicalwarps.mod.setdisplayname:
    description: Sets the display name of a warp
    default: op
  magicalwarps.mod.remove:
    description: Removes a warp
    default: op
  magicalwarps.mod.warpinfo:
    description: See info for a warp
    default: op
  magicalwarps.info:
    description: See info for MagicalWarps
    default: op
  magicalwarps.mod.reload:
    description: Reloads the config and storage of MagicalWarps
    default: op