name: FeelingsRelay
main: net.katsstuff.bukkit.feelingsrelay.FeelingsRelayPlugin
version: 1.1.2
api-version: 1.18
author: Katrix
depend: [DiscordSRV, ChatFeelings]
commands:
  feelingsrelay:
    description: Reload or get info about the plugin
permissions:
  feelingsrelay.admin:
    description: Configure the plugin
    default: op

libraries:
  - org.scala-lang:scala3-library_3:3.3.1
  - org.typelevel:cats-core_3:2.10.0
  - io.circe:circe-core_3:0.14.5
  - io.circe:circe-parser_3:0.14.5
  - net.katsstuff:perspective-derivation_3:0.2.0+17-d7d68444-SNAPSHOT